# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0005_auto_20171118_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkItemTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.PositiveIntegerField()),
                ('homework_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.HomeworkItem')),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('homework_item_timers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practices.HomeworkItemTimer')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='homeworkitemtimer',
            name='practice_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practices.Practice'),
        ),
    ]
