# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='lessons',
            field=models.ManyToManyField(to='lessons.Lesson'),
        ),
        migrations.AddField(
            model_name='homeworkitem',
            name='lessons',
            field=models.ManyToManyField(to='lessons.Lesson'),
        ),
    ]
