# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20171025_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='lessons.Attachment'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_items',
            field=models.ManyToManyField(blank=True, to='lessons.HomeworkItem'),
        ),
    ]
