# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20171025_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='homeworkitem',
            name='lessons',
        ),
    ]
