# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20171025_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='lessons',
            field=models.ManyToManyField(to='lessons.Lesson'),
        ),
        migrations.AddField(
            model_name='homeworkitem',
            name='lessons',
            field=models.ManyToManyField(to='lessons.Lesson'),
        ),
    ]
