# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20171118_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='homeworkitem',
            unique_together=set([('name', 'proficiency')]),
        ),
    ]
